hooks:
  before:init: make build
git:
  commit: false
  tag: true
  push: true
  requireCleanWorkingDir: false
github:
  release: true
  assets:
    - bin/gh-release-pr-generator
npm:
  publish: false
