name: Generate Release Page
on:
  push:
    branches:
      - main
jobs:
  release-it:
    name: release-it
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all commits and tags (Ref: https://github.com/actions/checkout#usage)
      - name: Install go for generating bin file
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set commiter for release-it
        run: |
          git config --global user.name release-it
          git config --global user.email ci@example.com
      - name: Install release-it
        run: npm install -g release-it
      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: release-it --ci --increment patch
