name: Generate Release Pull Request
on:
  push:
    branches:
      - develop
jobs:
  gh-release-pr-generator:
    name: gh-release-pr-generator
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19.4
      - name: Install gh-release-pr-generator
        run: go install github.com/nekonenene/gh-release-pr-generator@latest
      - name: Run gh-release-pr-generator
        run: gh-release-pr-generator --token ${{ secrets.GITHUB_TOKEN }} --repo-owner ${{ github.repository_owner }} --repo-name ${{ github.event.repository.name }} --dev-branch develop --prod-branch main
